using System;

using Shouldly;

using Xunit;

namespace D47.Panel.Tests;

/// <summary>
/// A held key is one press. Tier 1 and in process — no desktop, no keyboard,
/// and deliberately so: a keyboard's repeat cannot be synthesized at all,
/// because auto-repeat is generated by the hardware rather than by an injected
/// key that is never released. The only way to assert this behaviour is to hand
/// it the messages a repeat would produce.
/// </summary>
public class RepeatGuardTests
{
    /// <summary>
    /// What Windows does with a held key: nothing for the repeat delay, then a
    /// message every thirty milliseconds or so until it is let go.
    /// </summary>
    private static readonly TimeSpan RepeatDelay = TimeSpan.FromMilliseconds(500);
    private static readonly TimeSpan BetweenRepeats = TimeSpan.FromMilliseconds(33);

    [Fact]
    public void Hotkey_WhenHeldDown_IsOnePressRatherThanAStreamOfThem()
    {
        var clock = new StoppedClock();
        var guard = new RepeatGuard(clock);

        guard.Allows().ShouldBeTrue("the press itself should get through");

        clock.Advance(RepeatDelay);
        guard.Allows().ShouldBeFalse("the first repeat is the same press continuing");

        for (int repeat = 0; repeat < 60; repeat++)
        {
            clock.Advance(BetweenRepeats);

            guard.Allows().ShouldBeFalse(
                $"repeat {repeat + 2} is still the same press, two seconds in");
        }
    }

    [Fact]
    public void Hotkey_WhenPressedAgainAfterLettingGo_IsASecondPress()
    {
        var clock = new StoppedClock();
        var guard = new RepeatGuard(clock);

        guard.Allows().ShouldBeTrue();

        clock.Advance(RepeatGuard.LongerThanAnyKeyboardRepeat);

        guard.Allows().ShouldBeTrue("a press after the quiet window is a new one");
    }

    [Fact]
    public void Hotkey_WhenPressedTwiceQuickly_CountsAsOne()
    {
        // Recorded rather than regretted. This is the cost of covering a repeat
        // delay that Windows lets a Commander set as high as a second, and for
        // a show-and-hide it is closer to a feature than a defect.
        var clock = new StoppedClock();
        var guard = new RepeatGuard(clock);

        guard.Allows().ShouldBeTrue();

        clock.Advance(TimeSpan.FromMilliseconds(200));

        guard.Allows().ShouldBeFalse();
    }

    /// <summary>
    /// A clock that only moves when told to.
    ///
    /// <para>
    /// Hand-written rather than <c>FakeTimeProvider</c>, which lives in a
    /// package this repository does not reference yet. The abstraction is still
    /// the framework's <see cref="TimeProvider"/> rather than an invented
    /// <c>IClock</c>, which is what <c>docs/decisions.md</c> is actually
    /// protecting against — but the package is the recorded preference, so this
    /// is a divergence and is flagged as one.
    /// </para>
    /// </summary>
    private sealed class StoppedClock : TimeProvider
    {
        private DateTimeOffset _now = new(2026, 1, 1, 0, 0, 0, TimeSpan.Zero);

        public override DateTimeOffset GetUtcNow() => _now;

        internal void Advance(TimeSpan by) => _now += by;
    }
}
