using D47.Panel;

using Shouldly;

using Xunit;

namespace D47.Tier1.Tests.Panel;

/// <summary>
/// A held key is one press; letting go and pressing again is two. Tier 1 and in
/// process — no desktop, no keyboard, and necessarily so: auto-repeat is
/// generated by the hardware, not by an injected key that is never released, so
/// the only way to assert this is to hand it the messages a repeat would
/// produce.
/// </summary>
public class HeldKeyTests
{
    [Fact]
    public void Hotkey_WhenHeldDown_IsOnePressRatherThanAStreamOfThem()
    {
        var held = new HeldKey();

        held.Allows().ShouldBeTrue("the press itself should get through");

        for (int repeat = 1; repeat <= 60; repeat++)
        {
            held.Allows().ShouldBeFalse(
                $"repeat {repeat} is the same press continuing, however long it goes on");
        }
    }

    [Fact]
    public void Hotkey_WhenLetGoAndPressedAgain_IsASecondPress()
    {
        var held = new HeldKey();

        held.Allows().ShouldBeTrue();
        held.LetGo();

        held.Allows().ShouldBeTrue("a press after the key came up is a new one");
    }

    [Fact]
    public void Hotkey_WhenTappedQuickly_CountsEveryTap()
    {
        // The case that sent the previous implementation back. A window of time
        // cannot allow this and also swallow a held key, because the first
        // repeat of a held key arrives later than the gap between two taps.
        // Nothing here mentions time at all, which is the point.
        var held = new HeldKey();

        for (int tap = 1; tap <= 5; tap++)
        {
            held.Allows().ShouldBeTrue($"tap {tap} is its own press");
            held.LetGo();
        }
    }

    [Fact]
    public void Hotkey_WhenLetGoWithoutHavingBeenHeld_IsHarmless()
    {
        // The key can come up when nothing was gating on it — the poller that
        // watches for release does not coordinate with anything else.
        var held = new HeldKey();

        held.LetGo();

        held.Allows().ShouldBeTrue();
    }
}
